<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Parent configuration' => 'Eltern Konfiguration',
    'Comment' => 'Kommentar',
    'Create a parameter' => 'Neuen Parameter anlegen',
    'Default value' => 'Standart Wert',
    'ID' => 'ID',
    'Manage Parameters' => 'Parameter Verwalten',
    'Module' => 'Modul',
    'On bootstrap (on/off)' => 'Beim Bootstrap (on/off)',
    'On bootstrap (search on/ON)' => 'Beim Bootstrap (Suche on/ON)',
    'Parameter' => 'Parameter',
    'Parameter has been created' => 'Parameter erzeugt am',
    'Parameter name' => 'Parameter Name',
    'Save' => 'Speichern',
    'Title' => 'Titel',
    'Update parameter' => 'Parameter aktuallisiert',
    'Value' => 'Wert',
];
